-- ============================================================
-- PROJECT: Maven Fuzzy Factory E-Commerce Analysis
-- TOOL: MySQL / MySQL Workbench
-- AUTHOR: Christopher Blanco
-- OBJECTIVE:
-- Analyze website growth, conversion performance,
-- marketing acquisition, and revenue efficiency.
--
-- DATA PERIOD: March 2012 - March 2015
-- NOTE:
-- March 2012 and March 2015 contain partial-month data.
-- Revenue metrics use gross order revenue before refunds.
-- ============================================================

USE maven_toy_store;

-- ============================================================
-- SECTION 1: DATA VALIDATION
-- ============================================================

-- 1. Website sessions validation
SELECT
    COUNT(*) AS total_sessions,
    MIN(created_at) AS first_session,
    MAX(created_at) AS last_session,
    COUNT(DISTINCT user_id) AS unique_users
FROM website_sessions;

-- 2. Website pageviews validation
SELECT
    COUNT(*) AS total_pageviews,
    COUNT(DISTINCT website_pageview_id) AS unique_pageview_ids,
    COUNT(DISTINCT website_session_id) AS sessions_with_pageviews
FROM website_pageviews;

-- 3. Orders validation
SELECT
    COUNT(*) AS total_orders,
    MIN(created_at) AS first_order,
    MAX(created_at) AS last_order,
    COUNT(DISTINCT primary_product_id) AS distinct_primary_products
FROM orders;

-- 4. Order items validation
SELECT
    COUNT(*) AS total_order_items,
    COUNT(DISTINCT order_item_id) AS unique_order_item_ids,
    COUNT(DISTINCT order_id) AS orders_with_items,
    COUNT(DISTINCT product_id) AS distinct_products
FROM order_items;

-- 5. Refunds validation
SELECT
    COUNT(*) AS total_refunds,
    COUNT(DISTINCT order_item_refund_id) AS unique_refund_ids,
    COUNT(DISTINCT order_item_id) AS refunded_items,
    COUNT(DISTINCT order_id) AS orders_with_refunds
FROM order_item_refunds;

-- ============================================================
-- SECTION 2: BUSINESS ANALYSIS
-- ============================================================

-- ------------------------------------------------------------
-- 1. WEBSITE SESSIONS & ORDER VOLUME TREND
-- Business Question:
-- How have website sessions and order volume evolved over time?
-- ------------------------------------------------------------

WITH monthly_sessions AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        COUNT(*) AS sessions
    FROM website_sessions
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
),
monthly_orders AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        COUNT(*) AS orders
    FROM orders
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
)
SELECT
    s.month,
    s.sessions,
    COALESCE(o.orders, 0) AS orders
FROM monthly_sessions s
LEFT JOIN monthly_orders o
    ON s.month = o.month
ORDER BY s.month;

-- ------------------------------------------------------------
-- 2. SESSION-TO-ORDER CONVERSION RATE
-- Formula: Orders / Sessions * 100
-- ------------------------------------------------------------

WITH monthly_sessions AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        COUNT(*) AS sessions
    FROM website_sessions
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
),
monthly_orders AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        COUNT(*) AS orders
    FROM orders
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
)
SELECT
    s.month,
    s.sessions,
    COALESCE(o.orders, 0) AS orders,
    ROUND((COALESCE(o.orders, 0) / s.sessions) * 100, 2) AS conversion_rate_pct
FROM monthly_sessions s
LEFT JOIN monthly_orders o
    ON s.month = o.month
ORDER BY s.month;

-- ------------------------------------------------------------
-- 3. MARKETING CHANNEL PERFORMANCE
-- Success metric: Website sessions generated by each channel.
-- ------------------------------------------------------------

WITH channel_sessions AS (
    SELECT
        CASE
            WHEN utm_source = 'gsearch' THEN 'Paid Search - gsearch'
            WHEN utm_source = 'bsearch' THEN 'Paid Search - bsearch'
            WHEN utm_source = 'socialbook' THEN 'Social'
            WHEN utm_source IS NULL
                 AND http_referer = 'https://www.gsearch.com'
                THEN 'Organic Search - gsearch'
            WHEN utm_source IS NULL
                 AND http_referer = 'https://www.bsearch.com'
                THEN 'Organic Search - bsearch'
            WHEN utm_source IS NULL
                 AND http_referer IS NULL
                THEN 'Direct'
            ELSE 'Other'
        END AS channel,
        COUNT(*) AS sessions
    FROM website_sessions
    GROUP BY channel
)
SELECT
    channel,
    sessions,
    ROUND(sessions * 100.0 / SUM(sessions) OVER (), 2) AS share_of_sessions_pct
FROM channel_sessions
ORDER BY sessions DESC;

-- ------------------------------------------------------------
-- 4. REVENUE PER ORDER
-- Formula: Total Revenue / Orders
-- ------------------------------------------------------------

SELECT
    DATE_FORMAT(created_at, '%Y-%m') AS month,
    COUNT(*) AS orders,
    ROUND(SUM(price_usd), 2) AS total_revenue,
    ROUND(AVG(price_usd), 2) AS revenue_per_order
FROM orders
GROUP BY DATE_FORMAT(created_at, '%Y-%m')
ORDER BY month;

-- ------------------------------------------------------------
-- 5. REVENUE PER SESSION
-- Formula: Total Revenue / Website Sessions
-- ------------------------------------------------------------

WITH monthly_sessions AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        COUNT(*) AS sessions
    FROM website_sessions
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
),
monthly_revenue AS (
    SELECT
        DATE_FORMAT(created_at, '%Y-%m') AS month,
        SUM(price_usd) AS total_revenue
    FROM orders
    GROUP BY DATE_FORMAT(created_at, '%Y-%m')
)
SELECT
    s.month,
    s.sessions,
    ROUND(COALESCE(r.total_revenue, 0), 2) AS total_revenue,
    ROUND(COALESCE(r.total_revenue, 0) / s.sessions, 2) AS revenue_per_session
FROM monthly_sessions s
LEFT JOIN monthly_revenue r
    ON s.month = r.month
ORDER BY s.month;

-- ============================================================
-- SECTION 3: SUPPORTING CHECKS
-- ============================================================

-- 1. Product catalog
SELECT
    product_id,
    product_name,
    created_at AS launch_date
FROM products
ORDER BY product_id;

-- 2. Multi-item orders
SELECT
    order_id,
    COUNT(*) AS item_count
FROM order_items
GROUP BY order_id
HAVING COUNT(*) > 1
ORDER BY order_id;

-- 3. Refund volume by product
SELECT
    p.product_name,
    COUNT(r.order_item_refund_id) AS refunds,
    ROUND(SUM(r.refund_amount_usd), 2) AS refunded_revenue
FROM order_item_refunds r
LEFT JOIN order_items oi
    ON r.order_item_id = oi.order_item_id
LEFT JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY refunds DESC;

-- ============================================================
-- END OF ANALYSIS
-- ============================================================
